:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]
:uri-gradle-docs: https://docs.gradle.org/current/userguide
:uri-gradle-init-scripts: {uri-gradle-docs}/init_scripts.html[Gradle init scripts]
:uri-github: https://github.com
:uri-shields: https://img.shields.io
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0]
:plugin-id: 9665-gradle-init-scripts
:plugin-name: teamcity-gradle-init-scripts-plugin
:uri-project: {uri-github}/rodm/{plugin-name}
:uri-download: https://plugins.jetbrains.com/plugin/{plugin-id}
:uri-version: {uri-shields}/jetbrains/plugin/v/{plugin-id}?label=TeamCity%20plugin
:uri-downloads: {uri-shields}/jetbrains/plugin/d/{plugin-id}?label=Downloads
:uri-build-history: {uri-project}/actions
:uri-build-status: {uri-project}/workflows/Build/badge.svg

= Gradle Init Scripts plugin

A {uri-teamcity} plugin that provides support for reusing {uri-gradle-init-scripts}
between build configurations.

image:{uri-build-status}?branch=master["Build Status", link="{uri-build-history}"]
image:{uri-version}["Version", link={uri-download}]
image:{uri-downloads}["Downloads", link="{uri-download}"]

== Features

* Upload Gradle initialization scripts to a project

* Apply an init script to a build step using the Gradle build runner

* Apply an init script to a build configuration as a Build Feature

* Shows the build configurations and templates using the script

* Reports missing scripts, unused scripts and invalid configurations on the Server Health page

* Supports saving scripts to the Versioned Settings VCS repository

=== Example Scripts

Example scripts can be found in the link:scripts[scripts] directory.

== Installation

* Download the plugin from {uri-jetbrains-plugin}[JetBrains TeamCity Plugin Repository].

* Go to the plugin list of your TeamCity installation at `&lt;TeamCity URL&gt;/admin/admin.html?item=plugins` and
click on the link _Upload plugin zip_ to install the downloaded plugin file.

* Restart TeamCity.

== Using the plugin

* Edit a project, on the Gradle Init Scripts page upload an init script.

* Edit a build configuration and either configure an init script for a build step using the Gradle runner or
add the Build Feature, Gradle Init Script, and select the init script to use.

== Kotlin DSL

The plugin extends the Kotlin DSL to support applying a Gradle init script to a Gradle build step or to each
Gradle build step in build configuration via a build feature.

=== Gradle build step

The example below shows applying an init script to a Gradle build step.

[source, kotlin]
----
    steps {
        gradle {
            tasks = "clean build"
            enableStacktrace = true
            jdkHome = "%env.JDK_18%"
            initScriptName = "init-script.gradle"
        }
    }
----

=== Gradle build feature

The example below shows applying an init script as a build feature.

[source, kotlin]
----
    features {
        gradleInitScript {
            scriptName = "init-script.gradle"
        }
    }
----

== Compatibility

The plugin is compatible with TeamCity 2018.1 and later and requires the build agent to be running with Java 8.

== License

This plugin is available under the {uri-apache-license}.
