= Gradle Init Scripts plugin
:uri-teamcity: https://www.jetbrains.com/teamcity/[TeamCity]
:uri-gradle-docs: https://docs.gradle.org/current/userguide
:uri-gradle-init-scripts: {uri-gradle-docs}/init_scripts.html[Gradle init scripts]
:uri-download: https://bintray.com/rodm/teamcity-plugins-generic/teamcity-gradle-init-scripts-plugin

A {uri-teamcity} plugin that provides support for reusing {uri-gradle-init-scripts}
between build configurations.

image:https://travis-ci.org/rodm/teamcity-gradle-init-scripts-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/rodm/teamcity-gradle-init-scripts-plugin"]
image:https://api.bintray.com/packages/rodm/teamcity-plugins-generic/gradle-init-scripts/images/download.svg[link="https://bintray.com/rodm/teamcity-plugins-generic/gradle-init-scripts/_latestVersion"]

## Features

* Upload Gradle initialization scripts to a project

* Apply a script to a build configuration as a Build Feature

* Shows the build configurations and templates using the script

* Reports missing scripts, unused scripts and invalid configurations on the Server Health page

### Example Scripts

Example scripts can be found in the link:scripts[scripts] directory.

## Installation

* Download the plugin file from {uri-download} (see _Downloads_ section at the bottom of the page).

* Go to the plugin list of your TeamCity installation at `&lt;TeamCity URL&gt;/admin/admin.html?item=plugins` and
click on the link _Upload plugin zip_ to install the downloaded plugin file.

* Restart TeamCity.

## Using the plugin

* Edit a project, on the Gradle Init Scripts page upload an init script.

* Edit a build configuration and add the Build Feature, Gradle Init Script, and select the init script to use.

## Compatibility

The plugin is compatible with TeamCity 10.0 and later.

## License

This plugin is available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0].
