= Example Gradle Initialization Scripts
:uri-gradle-docs: https://docs.gradle.org/current/userguide
:uri-gradle-init-script-plugins: {uri-gradle-docs}/init_scripts.html#sec:init_script_plugins[Init script plugins]

To use the scripts select a project to edit then select the 'Gradle Init Scripts' settings page. Upload the
script using the 'Upload init script' button, then select a build configuration and add the Build Feature
'Gradle Init Script' selecting the script to use.

* `enterprise-repository.gradle` - replaces Maven repositories with a single enterprise repository URL.
This script is based on the example in the Gradle {uri-gradle-init-script-plugins} documentation. The script
requires the environment variable `REPO_URL` to be set with the URL of the enterprise repository to be used.

* `task-outcomes.gradle` - collects the execution outcomes of all the Gradle tasks in a build configuration and
outputs the counts as TeamCity statistics values. The statistics values can be used to add a new graph to the
build configurations statistics page.
