
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 1.8
      - name: Build using Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -s build
